import { PaginateConfig } from 'nestjs-paginate';
import { Drug } from '../entities/drug.entity';
import { FilterOperator, FilterSuffix } from 'nestjs-paginate';

export const DRUG_PAGINATION_CONFIG: PaginateConfig<Drug> = {
  sortableColumns: [
    'drug_id',
    'name',
    'price',
    'oldprice',
    'company',
    'units',
    'sold_times',
    'date_updated',
    'created_at',
  ],
  nullSort: 'last',
  defaultSortBy: [['created_at', 'DESC']],
  searchableColumns: [
    'name',
    'description',
    'company',
    'barcode',
    'active_raw',
    'dosage_form',
  ],
  select: [
    'drug_id',
    'original_id',
    'name',
    'oldprice',
    'price',
    'active_raw',
    'img',
    'description',
    'company',
    'dosage_form',
    'units',
    'barcode',
    'route',
    'pharmacology',
    'sold_times',
    'date_updated',
    'cosmo',
    'created_at',
  ],
  filterableColumns: {
    name: [FilterOperator.EQ, FilterOperator.ILIKE, FilterSuffix.NOT],
    price: [
      FilterOperator.EQ,
      FilterOperator.GT,
      FilterOperator.GTE,
      FilterOperator.LT,
      FilterOperator.LTE,
      FilterOperator.BTW,
    ],
    oldprice: [
      FilterOperator.EQ,
      FilterOperator.GT,
      FilterOperator.GTE,
      FilterOperator.LT,
      FilterOperator.LTE,
      FilterOperator.BTW,
    ],
    company: [FilterOperator.EQ, FilterOperator.ILIKE, FilterSuffix.NOT],
    dosage_form: [FilterOperator.EQ, FilterOperator.ILIKE],
    barcode: [FilterOperator.EQ],
    units: [
      FilterOperator.EQ,
      FilterOperator.GT,
      FilterOperator.GTE,
      FilterOperator.LT,
      FilterOperator.LTE,
    ],
    sold_times: [
      FilterOperator.EQ,
      FilterOperator.GT,
      FilterOperator.GTE,
      FilterOperator.LT,
      FilterOperator.LTE,
    ],
    created_at: [
      FilterOperator.GT,
      FilterOperator.GTE,
      FilterOperator.LT,
      FilterOperator.LTE,
      FilterOperator.BTW,
    ],
  },
  maxLimit: 100,
  defaultLimit: 20,
};
